[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "EMAIL_FROM,EMAIL_HOST,EMAIL_PASSWORD,EMAIL_PORT,EMAIL_USER,FIREBASE_API_KEY,AIzaSyA0L0jXgqwTa7_62RsA7fJAZWTVPom-lD4"
  SECRETS_SCAN_OMIT_PATHS = "*.html,*.js"

